In [3]:
import pandas as pd
import numpy as np

In [4]:
cv = pd.read_csv('./500feat_cv.csv')

In [5]:
cv.head()

,Unnamed: 0,10,100,able,absolutely,act,actually,add,advice,age,...,years,yes,young,younger,youtube,target,i_e,s_n,t_f,j_p
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,16,INFJ,0,1,1,0
1,1,1,0,1,0,0,0,0,1,0,...,0,0,0,0,1,ENTP,1,1,0,1
2,2,1,0,1,2,0,2,0,0,0,...,4,1,0,0,3,INTP,0,1,0,1
3,3,0,0,2,0,0,2,0,0,0,...,0,0,0,0,2,INTJ,0,1,0,0
4,4,0,0,0,0,0,1,0,0,0,...,0,2,0,0,1,ENTJ,1,1,0,0

In [7]:
X = cv.drop(cv[['target','Unnamed: 0','i_e','s_n','t_f','j_p']], axis=1)
y_i_e = cv.i_e
y_s_n = cv.s_n
y_t_f = cv.t_f
y_j_p = cv.j_p

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score, train_test_split

In [9]:
X_train, X_test, y_f_train, y_f_test = train_test_split(X,y_t_f, random_state=42)

In [10]:
logregf = LogisticRegression()

In [11]:
logregf.fit(X_train,y_f_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [12]:
kfold = StratifiedKFold()
cross_val_score(logregf, X_test, y_f_test, cv=kfold, scoring='accuracy').mean()

0.7441217150760719

In [13]:
df = pd.read_csv('./1000feat_cv.csv')

In [14]:
X = df.drop(df[['target','i_e','s_n','t_f','j_p']], axis=1)
y_i_e = df.i_e
y_s_n = df.s_n
y_t_f = df.t_f
y_j_p = df.j_p

In [15]:
X_train, X_test, y_f_train, y_f_test = train_test_split(X,y_t_f, random_state=42)

In [16]:
logreg = LogisticRegression()

In [17]:
logreg.fit(X_train,y_f_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [18]:
kfold = StratifiedKFold()
cross_val_score(logreg, X_test, y_f_test, cv=kfold, scoring='accuracy').mean()

0.7667127708621484

In [19]:
#remember that baseline is 54, score is 76! :)

In [20]:
df = pd.DataFrame(zip(logreg.coef_.T, X_train.columns))
df.columns = ['coef','word']

In [21]:
df.coef = [x[0] for x in df.coef]

In [22]:
df['abs'] = abs(df.coef)

In [23]:
df = df[['word','abs','coef']]

In [24]:
#most important words for predicting T or F
df.sort_values('abs', ascending=False).head(25)

             word       abs      coef
929        values  0.734605  0.734605
810  specifically  0.599249  0.599249
69      beginning  0.574852  0.574852
727      research  0.538542 -0.538542
88      boyfriend  0.531693  0.531693
748        scared  0.527562  0.527562
445         infjs  0.513919  0.513919
987         wrote  0.505148  0.505148
270     everybody  0.503622  0.503622
447          infp  0.468158  0.468158
38        answers  0.456739 -0.456739
260         entjs  0.453574 -0.453574
706        rarely  0.437230 -0.437230
676      possibly  0.435634 -0.435634
459          intj  0.435516 -0.435516
461          intp  0.431985 -0.431985
916      universe  0.430728 -0.430728
137   comfortable  0.429401  0.429401
296           fan  0.410848 -0.410848
860         terms  0.408237  0.408237
438       imagine  0.407835 -0.407835
578       minutes  0.404093 -0.404093
945          warm  0.394957  0.394957
311        female  0.392805 -0.392805
128       closest  0.387020  0.387020

In [25]:
torf_predictors = df.sort_values('abs', ascending=False).head(25)
torf_predictors.to_csv('./Word Lists/torf_predictors.csv')

In [26]:
#highest predictors of Feeling
df.sort_values('coef', ascending=False).head(25)

             word       abs      coef
929        values  0.734605  0.734605
810  specifically  0.599249  0.599249
69      beginning  0.574852  0.574852
88      boyfriend  0.531693  0.531693
748        scared  0.527562  0.527562
445         infjs  0.513919  0.513919
987         wrote  0.505148  0.505148
270     everybody  0.503622  0.503622
447          infp  0.468158  0.468158
137   comfortable  0.429401  0.429401
860         terms  0.408237  0.408237
945          warm  0.394957  0.394957
128       closest  0.387020  0.387020
625         older  0.382463  0.382463
401       helpful  0.380560  0.380560
252          enfp  0.376247  0.376247
934         voice  0.374949  0.374949
658         phone  0.372849  0.372849
470          isfj  0.368075  0.368075
444          infj  0.366347  0.366347
632      opinions  0.364565  0.364565
827       strange  0.360391  0.360391
771           shy  0.352540  0.352540
448         infps  0.350377  0.350377
719       related  0.346831  0.346831

In [31]:
t_predictors = df.sort_values('coef', ascending=False).head(25)
t_predictors.to_csv('./Word Lists/t_predict.csv')

In [28]:
#highest predictors of THINKING
df.sort_values('coef', ascending=True).head(25)

         word       abs      coef
727  research  0.538542 -0.538542
38    answers  0.456739 -0.456739
260     entjs  0.453574 -0.453574
706    rarely  0.437230 -0.437230
676  possibly  0.435634 -0.435634
459      intj  0.435516 -0.435516
461      intp  0.431985 -0.431985
916  universe  0.430728 -0.430728
296       fan  0.410848 -0.410848
438   imagine  0.407835 -0.407835
578   minutes  0.404093 -0.404093
311    female  0.392805 -0.392805
261      entp  0.379295 -0.379295
751     score  0.375147 -0.375147
144  computer  0.364695 -0.364695
997     young  0.364166 -0.364166
246  emotions  0.354215 -0.354215
433  identify  0.353754 -0.353754
273     exact  0.352789 -0.352789
315   figured  0.351977 -0.351977
84     boring  0.344060 -0.344060
262     entps  0.332601 -0.332601
468  involved  0.331821 -0.331821
615   noticed  0.330726 -0.330726
154   contact  0.325264 -0.325264

In [29]:
f_predictors = df.sort_values('coef', ascending=False).head(25)
f_predictors

             word       abs      coef
929        values  0.734605  0.734605
810  specifically  0.599249  0.599249
69      beginning  0.574852  0.574852
88      boyfriend  0.531693  0.531693
748        scared  0.527562  0.527562
445         infjs  0.513919  0.513919
987         wrote  0.505148  0.505148
270     everybody  0.503622  0.503622
447          infp  0.468158  0.468158
137   comfortable  0.429401  0.429401
860         terms  0.408237  0.408237
945          warm  0.394957  0.394957
128       closest  0.387020  0.387020
625         older  0.382463  0.382463
401       helpful  0.380560  0.380560
252          enfp  0.376247  0.376247
934         voice  0.374949  0.374949
658         phone  0.372849  0.372849
470          isfj  0.368075  0.368075
444          infj  0.366347  0.366347
632      opinions  0.364565  0.364565
827       strange  0.360391  0.360391
771           shy  0.352540  0.352540
448         infps  0.350377  0.350377
719       related  0.346831  0.346831

In [32]:
f_predictors.to_csv('./Word Lists/f_predict.csv')